# Generated by Django 4.2.5 on 2023-10-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recipie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='recipie_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
